kaogeek/kaogeek-discord-bot

.eslintrc.cjs
.prettierrc.cjs
package.json
pnpm-lock.yaml
tsconfig.json

feat: eslint and prettier

---

.eslintrc.cjs
.gitignore
src/client.ts
src/events/ready.ts
src/types/command-handler-config.types.ts
src/types/event-handler-config.types.ts
src/utils/validate-handler-config.ts

This PR is to add stricter typings to the project.

refactor: add typings

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/feature.md

Issue Template for **feature request** and **bug report**.

Issue Template

---

.prettierrc.cjs
src/client.ts
src/types/command-handler-config.types.ts
src/types/event-handler-config.types.ts
src/utils/validate-handler-config.ts

When add new line without the trailing comma, version control show this as two changed lines, which might lead to merge conflict. This pr reduce that from happens.

use trailingComma: 'all' which is better for git

---

src/client.ts
src/commands/Moderators/user.ts
src/events/interactionCreate.ts
src/types/command-handler-config.types.ts

Added snippets for user right clicks and private responses.

added: snippets for user right clicks and private responses.

---

.gitignore
src/keyv.ts

[added: check folder: ./.data/ Datastore files is exists](https://github.com/masuru-aomsin/kaogeek-discord-bot/commit/ab7929c5a85c2825f9f63aac9067fcc327f93fbc)

check folder "./.data/" Datastore files is exists

---

src/commands/moderators/report.ts
src/commands/moderators/user.ts

Just improve existing bot reply to use embed instead.
Btw, if you have any bot feature I can make, let me know.

Beautify bot reply using embed

---

.github/workflows/checks.yml
package.json

Add new job for type checking, also use `node-version-file` to sync node version with project.

add check type to ci

---

package.json
src/events/preventEmojiSpam.ts

Add `--max-warnings=0` to `lint` script so that build fail if there is a warning in codebase.

make eslint warnings errors

---

.prettierrc.cjs
package.json
src/config.ts
src/events/preventEmojiSpam.ts
tsconfig.json

- Set `moduleResolution` to `nodeNext` to prevent runtime errors

chore: set moduleResolution to nodenext

---

src/events/preventEmojiSpam.ts

This pull request addresses the issue where the bot was failing to correctly identify and handle messages consisting of multiple emojis.

Improve Multi-Emoji Handling in Message Content

---

.github/workflows/deployment.yml

ci: add deployment pipeline

---

.env.example
.gitignore
.tool-versions
README.md

- Add node lts-hydrogen to .tool-versions (asdf)
- Update readme for setting up Discord & env vars
- Update .env.example
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Update readme for dev setup

---

src/client.ts

Clean up unused code, unnecessary condition

refactor: cleanup client.ts

---

src/client.ts
src/types/CommandHandlerExecutor.ts
src/types/EventHandlerExecutor.ts

Update method name so people can understand code easier

refactor: update method name

---

src/client.ts

improve smoke tests to protect against the case where some handlers fail to be imported.

improve smoke tests to load handlers

---

.github/renovate.json

We won't update nodejs to 20 until LTS arrive.

ci: disable nodejs in renovate

---

package.json
pnpm-lock.yaml
src/client.ts
src/commands/index.ts
src/events/index.ts

Change to static import to reduce risk of errors from reading file during runtime.
TODO: Docs (Maybe in other PR?)

refactor: static import

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/feature.md
README.md
package.json

That it
Also add step in readme for new dev

Add watch command for development

---

README.md

Just another step that user might need

add "install pnpm" at setup step

---

src/events/guildMemberAdd.ts
src/events/guildMemberRemove.ts
src/events/guildMemberUpdate.ts
src/events/index.ts

one of the moderators sent me a tip that if a discord user has a "flagged" role, and they leave the channel and rejoin, they are no longer flagged.
so we probably need to inspect guild member activities. this pr is to prepare for it — just add event handlers and log. more logic can be added later.

log role changes

---

.github/pull_request_template.md

make PR template request for screenshot

request for screenshot in PR template

---

.gitignore

This PR adds three files to gitignore (package-lock.json, .DS_Store, __MACOSX)
N/A

Add package-lock.json, .DS_Store and __MACOSX to gitignore

---

package.json
pnpm-lock.yaml

remove keyv from deps

---

.github/workflows/checks.yml

you can view test coverage result in GitHub Actions summary already, adding a comment in PR makes it more noisy

do not comment test coverage; just step summary is enough

---

src/commands/moderators/user.ts
src/commands/runtimeConfig/inspectConfig.ts
src/commands/runtimeConfig/reloadConfig.ts

Discord.js have formatters utilities so might as well use it.
https://discordjs.guide/popular-topics/formatters.html
I leave bold (`** **`) as is because it's shorter.

use discord.js formatters utilities

---

bot-config.example.toml
prisma/schema.prisma
src/commands/index.ts
src/commands/nominations/nominate.ts
src/utils/RuntimeConfigurationSchema.ts

feature request by @vtno 
successful nomination — the bot will post in a channel for nominations
edge cases:
- nomination not enabled
- you don’t have the role (only contributors can nominate other contributors)
- the other person already is a contributor
- you already nominated that person

nominations

---

src/events/interactionCreate.ts

remove "deleteReply()" if "disableAutoDeferReply" is true

---

.eslintrc.cjs
package.json
src/features/profileInspector/index.ts

Merge duplicate import

---

.github/workflows/checks.yml

fix e2e smoke test

---

src/features/stickyMessage/stickyMessages.ts
src/utils/sendDm.ts

resolve https://github.com/kaogeek/kaogeek-discord-bot/issues/149
null

[FIX] Send DM Utils

---

src/features/profileInspector/index.ts
src/types/UserModerationLogEntry.ts

standardize moderation log type by using modeartion log type enum intead of custom string.

standardize moderation log type 

---

src/features/index.ts

add slowmode feature to feature list
i missed it while refactoring, sorry
N/A

add slowmode to feature list

---

.github/renovate.json

Enable lockfile maintenance to keep dependencies up to date

chore: enable lockfile maintenance

---

src/features/preventEmojiSpam/index.ts

The current logging does not give enough information whether the system is working on the intended channel or not.

improve emoji logging

---

src/features/tempRole/index.ts

Rename temp-role to tempRole (I missed this change before it merged 😂)

Rename temp-role to tempRole

---

src/features/preventEmojiSpam/isEmojiPreventionEnabled.ts

Fixbug preventEmojiSpam bypass role not work correct

Fixbug preventEmojiSpam bypass role not work correct

---

package.json
pnpm-lock.yaml

chore(deps): bump vitest

---

package.json
pnpm-lock.yaml
src/features/nameChecker/checkName.ts
src/features/nameChecker/checkNameAgainstPatterns.spec.ts
src/features/nameChecker/checkNameAgainstPatterns.ts
src/utils/RuntimeConfigurationSchema.ts

Add support Zalgo Name Check becuse some user using Zalgo and Hard to ping user or someone report user via screenshot Moderatorhard to search user

Add support Zalgo Name Check

---

README.md

Closes #105
Update deployment and logs docs
N/A

Update deployment and logs docs
