package.json
pnpm-lock.yaml
tsconfig.json

Why?
- `tsx` uses `esbuild` to compile JavaScript code which is faster.
- `tsx` supports watch mode: `tsx watch src/client.ts` — no nodemon needed.
Also:
- used `@tsconfig/node18` as a base configuration to simply tsconfig file.

switch from ts-node to tsx

---

Dockerfile
package.json
pnpm-lock.yaml

Current Dockerfile image is massive. This is because of layer sizes produced by installing all dependencies including `devDependencies`.
tl;dr change Dockerfile to be multi-stage build only include what *actually* needs to run on production with OS mostly stripped out.
Total image size gone down from **446MB** to **188MB**

Dockerfile optimization

---

src/client.ts

Fix so it can read command on windows (in case we have contributor using windows), while still work on linux. I don't have macos but I guess it still work.

fix cannot read commands on windows

---

src/commands/info/ping.ts
src/events/interactionCreate.ts

Right now the `/ping` command posts the result to the server. This can be annoying.
Also removed shit code made earlier lol
1st message is before
2nd message is after

make ping command ephemeral

---

src/events/ready.ts

global application commands are cached for 1 hour. this makes it janky to update. guild commands update immediately.

use guild commands instead of global application commands

---

.github/workflows/checks.yml
.gitignore

- Using concurrency in CI to cancel any in-progress job to run as a higher-priority waiting request.
- ignore yarn.lock

ci: Using concurrency to cancel any in-progress job

---

package.json
prisma/schema.prisma
src/commands/index.ts
src/commands/moderators/inspectProfile.ts
src/commands/moderators/user.ts
src/events/index.ts
src/features/profileInspector/index.ts
src/types/EventHandlerConfig.ts
src/utils/ActionSet.ts
src/utils/prompt.ts

Added a feature to inspect profile.
Two utilities has been added:
- `ActionSet` — for improving buttons.
- `prompt` — for requesting text from user.
- Option 1: Right click on a message &rarr; Inspect user profile
- Option 2: Slash command
- Option 3: Right click user &rarr; Inspect profile
When inspecting user profile, it shows
- basic info
- the number of strikes the user currently has
- recent moderation log for this user
- buttons to add strike or reset strike
When adding a strike it prompts for a reason.
Right now getting a strike does not do anything.

‍profile inspector

---

src/commands/info/ping.ts
src/commands/moderators/deleteAllMessage.ts
src/commands/moderators/inspectProfile.ts
src/commands/moderators/report.ts
src/commands/moderators/user.ts
src/events/guildMemberAdd.ts
src/events/guildMemberRemove.ts
src/events/guildMemberUpdate.ts
src/events/interactionCreate.ts
src/events/preventEmojiSpam.ts
src/events/ready.ts
src/types/defineCommandHandler.ts
src/types/defineEventHandler.ts

by using `satisfies`
- there is more type annotation (some people prefer less type annotations. e.g. [“I love TypeScript. I try to use it as little as possible. And that's a good thing.” —Theo (2023)](https://youtu.be/Xl02L1jy53c))
- have to write the same type 2 times
this PR creates type utility: `defineCommandHandler`
- this reduces type annotations
- no more duplicate types
this “define” system is adopted in many modern TS ecosystems
- Astro: `defineConfig` https://docs.astro.build/en/guides/configuring-astro/
- Playwright: `defineConfig` https://playwright.dev/docs/test-configuration
- Vite: `defineConfig` https://vitejs.dev/config/#config-intellisense
see above

use type helpers

---

src/commands/index.ts
src/commands/moderators/activeThreads.ts
src/utils/ActionSet.ts

the server has a problem with too many threads.
last night i asked a moderator about what kind of automation would be most valuable, it is: threads pruning.
this PR prepares the way to go forward. start by letting moderators check how many active threads are there.
later PR can extend this command to provide functionality to, e.g. generate a report or prune oldest threads or more.

add active threads command

---

src/client.ts
src/commands/info/ping.ts
src/commands/moderators/activeThreads.ts
src/commands/moderators/deleteAllMessage.ts
src/commands/moderators/inspectProfile.ts
src/commands/moderators/report.ts
src/commands/moderators/user.ts
src/events/guildMemberAdd.ts
src/events/guildMemberRemove.ts
src/events/guildMemberUpdate.ts
src/events/interactionCreate.ts
src/events/preventEmojiSpam.ts
src/events/ready.ts
src/features/profileInspector/index.ts
src/types/BotContext.ts
src/types/CommandHandlerExecutor.ts
src/types/EventHandlerExecutor.ts

this PR introduces a `BotContext` interface
- it removes cyclic dependency: `client.ts` &rarr; `CommandHandlerConfig.ts` &rarr; `CommandHandlerExecutor.ts` &rarr; `client.ts`
- we can send different context to different event handler. for example, in the future we can add debugging facilities or more structured logging.
N/A, refactor only, no change in behavior
application runs properly

introduce BotContext interface

---

src/events/preventEmojiSpam.ts
test/spec/utils/isOnlyEmoji.spec.ts

the bot deletes messages with only numbers

HOTFIX: disable emoji deletion for now

---

src/utils/isOnlyEmoji.spec.ts
src/utils/isOnlyEmoji.ts

reopen from https://github.com/kaogeek/kaogeek-discord-bot/pull/127 due to a low quality commit msg
1. updated `isOnlyEmoji` now also checks for the Combining Enclosing Keycap (0x20E3), which is _another way_ to create keycap number emojis (like 1️⃣, 2️⃣, 3️⃣, etc) 
- we can test it by copying a string from `isOnlyEmoji.spec.ts` at line 23
2. refactor the function for more readability.
3. add more test case
//emoji behaviour is so weird

fix feature : update isOnlyEmoji

---

.eslintrc.cjs

Setting `prettier/prettier` to `warn` so that it is a bit more friendly for our eyes when we don't finish typing something.
Since we allow no more than 0 warnings, this has no difference.

chore: make prettier warn

---

bot-config.example.toml
src/events/guildMemberAdd.ts
src/events/guildMemberUpdate.ts
src/events/index.ts
src/events/messageCreate.ts
src/features/nameChecker/checkNameAgainstPatterns.spec.ts
src/features/nameChecker/checkNameAgainstPatterns.ts
src/features/nameChecker/index.ts
src/utils/RuntimeConfigurationSchema.ts

some people are setting names that moderators consider offensive or inappropriate, moderators said "Flag จนเมื่อยมือออ"
this PR implements rudimentary name checking. it is done lazily - when a guild member posts a message or when they became active or change their name or join the server

name checking

---

src/commands/index.ts
src/commands/moderators/slowmode.ts

reduce time to set slowmode per channel (set slowmode for all text channels at the same time)

add slowmode command

---

src/Bot.ts
src/events/index.ts
src/events/preventEmojiSpam.ts
src/events/stickyMessageHandler.ts
src/events/stickyMessageRemove.ts
src/events/stickyMessageSet.ts
src/types/Plugin.ts
src/types/PluginContext.ts
src/types/defineEventHandler.ts
src/types/definePlugin.ts

right now the "events" folder start looking messy because it contains a mix of 3 things
- index file
- file named after an actual event
- file named after a functionality/feature
to fix this, i want to introduce a plugin system. each feature will be able to register multiple event handlers and commands. this refactor is being done in incremental steps.
- **step 1** (this PR) — introduce a plugin system and redefine event handlers in terms of plugins (avoid API changes)
- **step 2** — move event handlers from `events` folder into individual feature in the `features` folder
- **step 3** — introduce support for defining [application commands](https://discord.com/developers/docs/interactions/application-commands) inside a plugin
- **step 4** — move commands from the `commands` folder into …

begin moving towards plugin system

---

src/Bot.ts
src/commands/index.ts
src/commands/moderators/activeThreads.ts
src/commands/nominations/nominate.ts
src/types/PluginContext.ts
src/types/defineCommandHandler.ts

this PR updates `defineCommandHandlers` to be implemented in terms of plugin
- **step 1** ~~introduce a plugin system and redefine event handlers in terms of plugins (avoid API changes)~~
- see: #143
- **step 2** — move event handlers from `events` folder into individual feature in the `features` folder
- see #144 
- **step 3 (this PR)** — introduce support for defining [application commands](https://discord.com/developers/docs/interactions/application-commands) inside a plugin
- **step 4** — move commands from the `commands` folder into individual feature in the `features` folder

plugin system part 3: define command handler in terms of plugin

---

src/Bot.ts

i used the wrong method to register an interaction handler
N/A

HOTFIX: interaction event handler registered with `once` instead of `on`

---

src/features/stickyMessage/stickyMessages.spec.ts
src/features/stickyMessage/stickyMessages.ts

silent means it won't broadcast any push/desktop notification
Even though server this big Discord default notification to "only @mentions", but just in case anyway.
silent message have this cool icon

Make sticky message silent

---

Dockerfile
smoke/docker-compose.yml
src/Bot.ts
src/features/memberUpdateLogger/index.ts
src/features/messagePruner/pruneMessagesCommand.ts
src/features/nameChecker/checkName.ts
src/features/nameChecker/checkNameAgainstPatterns.ts
src/features/nameChecker/index.ts
src/features/preventEmojiSpam/index.ts
src/features/stickyMessage/index.ts
src/features/stickyMessage/stickyMessageHandler.spec.ts
src/features/stickyMessage/stickyMessageHandler.ts
src/features/stickyMessage/stickyMessageRemove.ts
src/features/stickyMessage/stickyMessageSet.ts
src/features/stickyMessage/stickyMessages.spec.ts
src/features/stickyMessage/stickyMessages.ts
src/index.ts
src/types/BotContext.ts
src/types/Logger.ts
src/types/PluginContext.ts
src/utils/createLogger.ts

when many events are happening at once, we want to be able to differentiate between errors between event A vs event B
this PR
- introduces a `Logger` interface
- update all features to use the logger
- send a logger with different prefix to each command/event handler
there is feature specific code in bot’s code which is supposed to be generic
this PR
- introduces an initializer system
- any plugin that needs initialization logic can `addInitializer` during setup
- bot will wait for all initializers to finish before logging in
when an event handler encounters a problem, **the bot crashes**
this PR
- adds a try-catch handler in the event listener, so when there is an error, it is logged, but it doesn’t crash the bot
in the above picture, each event has a unique ID. when searching log, we …

add a logger module + initializers system + event handler error handling

---

bot-config.example.toml
src/features/preventEmojiSpam/index.ts
src/features/preventEmojiSpam/isEmojiPreventionEnabled.spec.ts
src/features/preventEmojiSpam/isEmojiPreventionEnabled.ts
src/utils/RuntimeConfigurationSchema.ts

Allow enabling `preventEmojiSpam` on some channels. Why? Some people flood emoji in Stage channel.
N/A

allow enabling `preventEmojiSpam` on some channels

---

README.md
package.json
pnpm-lock.yaml

This PR includes
- Update pnpm lockfile to version 6.1 because someone accidently mess with lockfile
- Update docs to encourage dev to use corepack
- No longer allow node 16 and old version of pnpm
`corepack enable` and corepack manage pnpm version for you.
When you switch to another project (switching directory). pnpm version is automatically switched based on what is set on that project.

docs: encourage dev to use corepack

---

.github/renovate.json

Renovate should now group all non-major dependencies into a single PR. Should reduce number of PRs that it open.

chore: group renovate deps

---

src/features/nameCleansing/nameCleansing.ts

Improve performance ref - https://github.com/kaogeek/kaogeek-discord-bot/pull/201

Improve performance nameCleansing

---

.github/workflows/deployment.yml
Dockerfile

Seems like `registry.yue.sh` is down.
To optimize, we are migrating to GitHub Packages instead.
- Docker package is now published publicly here: <https://github.com/kaogeek/kaogeek-discord-bot/pkgs/container/kaogeek-discord-bot>
- Used the official action to build image. This makes image build faster (reduce time to deploy by ~1.5 minute).

upload image to public ghcr registry

---

.github/workflows/checks.yml

Change to number version so renovate can handle it better.

chore(deps): use version number for gh actions
